--1 Find the app with an ID of 1880.
-- playstore=# SELECT app_name FROM analytics WHERE id = '1880';
--         app_name         
-- -------------------------
--  Web Browser for Android
-- (1 row)

--2 Find the ID and app name for all apps that were last updated on August 01, 2018.
-- playstore=# SELECT id, app_name FROM analytics WHERE last_updated = '2018-08-01';
--   id  |                                     app_name                                      
-- ------+-----------------------------------------------------------------------------------
--    10 | Clash Royale
--    11 | Candy Crush Saga
--    12 | UC Browser - Fast Download Private & Secure
--    74 | Score! Hero
--   101 | Tiny Flashlight + LED
--   102 | Crossy Road
--   103 | SimCity BuildIt
--   111 | FIFA Soccer
--   112 | Angry Birds 2
--   125 | Need for Speed™ No Limits
--   126 | YouCam Makeup - Magic Selfie Makeovers
--   152 | Fallout Shelter
--   159 | DU Recorder – Screen Recorder, Video Editor, Live
--   160 | Bike Race Free - Top Motorcycle Racing Games
--   161 | KakaoTalk: Free Calls & Text
--   162 | Dolphin Browser - Fast, Private & Adblock🐬
--   163 | Opera Browser: Fast and Secure
--   164 | MARVEL Contest of Champions
--   184 | Video Editor Music,Cut,No Crop
--   226 | Frozen Free Fall
--   260 | Chess Free

--3 Count the number of apps in each category, e.g. “Family | 1972”.
-- playstore=# SELECT category, COUNT(category) FROM analytics GROUP BY category;
--       category       | count 
-- ---------------------+-------
--  BOOKS_AND_REFERENCE |   191
--  COMMUNICATION       |   342
--  BEAUTY              |    46
--  EVENTS              |    52
--  PARENTING           |    59
--  PHOTOGRAPHY         |   313
--  GAME                |  1110
--  BUSINESS            |   313
--  SOCIAL              |   269
--  MEDICAL             |   350
--  TOOLS               |   753
--  TRAVEL_AND_LOCAL    |   234
--  ART_AND_DESIGN      |    63
--  LIFESTYLE           |   319
--  WEATHER             |    79
--  COMICS              |    59
--  PRODUCTIVITY        |   360
--  PERSONALIZATION     |   329
--  FINANCE             |   331
--  SPORTS              |   338
--  ENTERTAINMENT       |   149

--4 Find the top 5 most-reviewed apps and the number of reviews for each.
-- playstore=# SELECT app_name, reviews FROM analytics ORDER BY reviews DESC LIMIT 5;
--                  app_name                 | reviews  
-- ------------------------------------------+----------
--  Facebook                                 | 78158306
--  WhatsApp Messenger                       | 78128208
--  Instagram                                | 69119316
--  Messenger – Text and Video Chat for Free | 69119316
--  Clash of Clans                           | 69109672
-- (5 rows)

--5 Find the app that has the most reviews with a rating greater than equal to 4.8.
-- playstore=# SELECT app_name, reviews, rating FROM analytics WHERE rating>='4.8' ORDER BY reviews DESC LIMIT 1;
--   app_name  | reviews | rating 
-- ------------+---------+--------
--  Chess Free | 4559407 |    4.8
-- (1 row)

--6 Find the average rating for each category ordered by the highest rated to lowest rated.
-- playstore=# SELECT category, AVG(rating) FROM analytics GROUP BY category ORDER BY AVG(rating) DESC;
--       category       |        avg         
-- ---------------------+--------------------
--  EVENTS              |  4.395238104320708
--  EDUCATION           |   4.38903223006956
--  ART_AND_DESIGN      |  4.347540949211746
--  BOOKS_AND_REFERENCE | 4.3423728633061645
--  PERSONALIZATION     |    4.3283387457509
--  BEAUTY              |  4.299999970656175
--  GAME                |  4.287167731498383
--  PARENTING           |  4.285714266251545
--  HEALTH_AND_FITNESS  | 4.2743944663902464
--  SHOPPING            |  4.253648051376507
--  SOCIAL              |  4.245669291244717
--  WEATHER             |   4.24399998664856
--  SPORTS              |  4.233333332576449
--  PRODUCTIVITY        |  4.212173904543338
--  AUTO_AND_VEHICLES   |  4.200000017881393
--  HOUSE_AND_HOME      |  4.197368430463891
--  PHOTOGRAPHY         |  4.196116511489967
--  MEDICAL             | 4.1926829182520144
--  FAMILY              | 4.1904873752761995
--  LIBRARIES_AND_DEMO  | 4.1784615259904125
--  FOOD_AND_DRINK      |  4.155660354866172


--7 Find the name, price, and rating of the most expensive app with a rating that’s less than 3.
-- playstore=# SELECT app_name, price, rating FROM analytics WHERE rating < 3 ORDER BY price DESC LIMIT 1;      app_name      | price  | rating 
-- --------------------+--------+--------
--  Naruto & Boruto FR | 379.99 |    2.9
-- (1 row)

--8 Find all apps with a min install not exceeding 50, that have a rating. Order your results by highest rated first.
-- playstore=# SELECT * FROM analytics WHERE rating >= 0 AND min_installs<=50 ORDER BY rating DESC;
--   id  |                    app_name                    |      category       | rating | reviews | size | min_installs | price | content_rating |        genres         | last_updated |  current_version   | android_version 
-- ------+------------------------------------------------+---------------------+--------+---------+------+--------------+-------+----------------+-----------------------+--------------+--------------------+-----------------
--  9468 | DT                                             | FAMILY              |      5 |       4 | 52M  |           50 |     0 | Everyone       | {Education}           | 2018-04-03   | 1.1                | 4.1 and up
--  9464 | DQ Akses                                       | PERSONALIZATION     |      5 |       4 | 31M  |           50 |  0.99 | Everyone       | {Personalization}     | 2018-04-27   | 1.1                | 4.1 and up
--  9453 | DM Adventure                                   | MEDICAL             |      5 |       4 | 25M  |            1 |     0 | Everyone       | {Medical}             | 2018-08-02   | 1.0.72             | 4.0.3 and up
--  9427 | db Meter - sound level meter with data logging | GAME                |      5 |       5 | 4.6M |           10 |     0 | Everyone       | {Racing}              | 2018-08-01   | 1.11               | 4.0.3 and up
--  9452 | Otto DM                                        | MEDICAL             |      5 |       4 | 2.5M |            5 |     0 | Everyone       | {Medical}             | 2018-08-03   | 1                  | 4.1 and up
--  9431 | ElejaOnline DF                                 | FAMILY              |      5 |       5 | 15M  |           50 |     0 | Everyone       | {Education}           | 2017-10-06   | 2.3.3              | 4:
-- playstore=# SELECT app_name FROM analytics WHERE rating >= 0 AND min_installs<=50 ORDER BY rating DESC;
--                     app_name                    
-- ------------------------------------------------
--  DT
--  DQ Akses
--  DM Adventure
--  db Meter - sound level meter with data logging
--  Otto DM
--  ElejaOnline DF
--  Labs on Demand
--  FK Events
--  My CW
--  Dr.Dice - Sic bo analyzer
--  BTK-FH Online Campus
--  EU Whoiswho
--  Wifi Mingle
--  Lord Fairfax EMS Council
--  E.U. Trademark Search Tool
--  Popsicle Launcher for Android P 9.0 launcher
--  Q Actions - Digital Assistant
--  Border Ag & Energy
--  AQ: First Contact
--  AQ wisdom +
--  AQ Dentals
--  British Columbia Transit Info
--  CI On The Go
--  Radio FG Paris Underground
--  BV Bombers
--  EC Designer 2.0
--  EP FCU
--  Pekalongan CJ
--  CQ SIGNAL PRO 5
--  HR Team CQ Region Ed Qld
--  iCluster - The DX-Cluster database
--  MY GULFPORT FL
--  Sensenuts eI
--  BW t&t
--  DT CLOTHINGS
--  Miller’s Bar B-Q
--  All-night drugstore CI & Price
--  CY Spray nozzle
--  DY Fitness
--  Custos F.O.
-- there are a lot of results here and the question was a bit non specific so I took sections from my results, once with the full table data and once with just the app_name's 

--9 Find the names of all apps that are rated less than 3 with at least 10000 reviews.
-- playstore=# SELECT app_name FROM analytics WHERE rating < 3 AND reviews > 10000;
--                     app_name                     
-- -------------------------------------------------
--  The Wall Street Journal: Business & Market News
--  Vikings: an Archer’s Journey
--  Shoot Em Down Free
-- (3 rows)


--10 Find the top 10 most-reviewed apps that cost between 10 cents and a dollar.
-- playstore=# SELECT app_name FROM analytics WHERE price BETWEEN .10 AND 1.00 ORDER BY reviews DESC LIMIT 10;
--                   app_name                   
-- ---------------------------------------------
--  Free Slideshow Maker & Video Editor
--  Couple - Relationship App
--  Anime X Wallpaper
--  Dance On Mobile
--  Marvel Unlimited
--  FastMeet: Chat, Dating, Love
--  IHG®: Hotel Deals & Rewards
--  Live Weather & Daily Local Weather Forecast
--  DreamMapper
--  Můj T-Mobile Business
-- (10 rows)

--11 Find the most out of date app. Hint: You don’t need to do it this way, but it’s possible to do with a subquery: http://www.postgresqltutorial.com/postgresql-max-function/
-- playstore=# SELECT app_name, last_updated FROM analytics ORDER BY last_updated LIMIT 1;
--   app_name  | last_updated 
-- ------------+--------------
--  CP Clicker | 2010-05-21
-- (1 row)

--12 Find the most expensive app (the query is very similar to #11).
-- playstore=# SELECT app_name, price FROM analytics ORDER BY price DESC LIMIT 1;
--       app_name      | price 
-- --------------------+-------
--  Cardi B Piano Game |   400
-- (1 row)

--13 Count all the reviews in the Google Play Store.
-- playstore=# SELECT SUM(reviews) FROM analytics;
--     sum     
-- ------------
--  4814575866
-- (1 row)

--14 Find all the categories that have more than 300 apps in them.
-- playstore=# SELECT category, COUNT(category) FROM analytics GROUP BY category HAVING COUNT(category)>300;
--     category     | count 
-- -----------------+-------
--  COMMUNICATION   |   342
--  PHOTOGRAPHY     |   313
--  GAME            |  1110
--  BUSINESS        |   313
--  MEDICAL         |   350
--  TOOLS           |   753
--  LIFESTYLE       |   319
--  PRODUCTIVITY    |   360
--  PERSONALIZATION |   329
--  FINANCE         |   331
--  SPORTS          |   338
--  FAMILY          |  1789
-- (12 rows)

--15 Find the app that has the highest proportion of min_installs to reviews, among apps that have been installed at least 100,000 times. Display the name of the app along with the number of reviews, the min_installs, and the proportion.
-- playstore=# SELECT app_name, reviews, min_installs, min_installs/reviews AS proportion_reviews_to_installs FROM
-- analytics WHERE min_installs>100000 ORDER BY min_installs/reviews LIMIT 10;
--                      app_name                     | reviews  | min_installs | proportion_reviews_to_installs 
-- --------------------------------------------------+----------+--------------+--------------------------------
--  Evie Launcher                                    |   348962 |      1000000 |                              2
--  360 Security - Free Antivirus, Booster, Cleaner  | 44891723 |    100000000 |                              2
--  Free Adblocker Browser - Adblock & Popup Blocker |   376223 |      1000000 |                              2
--  Inst Download - Video & Photo                    |   364013 |      1000000 |                              2
--  Wave Z Live Wallpaper                            |   167974 |       500000 |                              2
--  8 Ball Pool                                      | 44881447 |    100000000 |                              2
--  My Talking Tom                                   | 44891723 |    100000000 |                              2
--  Snapchat                                         | 44893888 |    100000000 |                              2
--  Google Play Movies & TV                          |  2721923 |     10000000 |                              3
--  Mobile Strike                                    |  2719142 |     10000000 |                              3
-- (10 rows)